# Civic Agent Based Model
# JonJon Clark et al.
# 17/07/2018


#Number of Monte Carlo Simulations to be executed
# We can simply start with one
MC=1 

#MONTE CARLO INVARIANT PARAMETERS SETTING

#Number of simulation rounds
Time=1000

# Reducing the scenairo to requesters and validators only
# Assume that requestors cannot be validators and vis versa intially

#Number of Requesters
# TV license, vodacom stores, banks lots of instituations
num_requesters = 500

#Number of Validators
num_validators = 10 # Think of these as big banking instituations etc...


#Firms’ price parameter: mean of Normal Distribution
alpha = 0.1
#Firms’ price parameter:variance of Normal Distribution
varpf = 0.4

# Other parameters to be introduced
# i.e. prices of validations etc...
# penalties for providing false attestations etc...

#number of validation requests received each round
totalrequests= 100000

#percentage which ahave false information
false_perce= 0.025

#probablity that false info found out by validators
validator_accuracy = 0.5

#probablity that true info flagged as false by validators
validator_inaccuracy = 0.005



# Aggregate results intialisation 
# aggreagates we keep track of to plot over simulation time

#define here what we want to keep track of
# 1) number of false attestations confirmed
# 2) total number of attentations confirmed etc...

#Aggregate revenue generated by Validators (Assuming fixed size of attestation market)
YY = matrix(data = 0, ncol = MC, nrow = time)

#etc add more KPI's



for (mc in 1:MC) {
  
  #Intial simulation set up
  print(paste("Monte Carlo N", mc))
  set.seed(mc) # keep the seed the same for sensitivity ananlysis
  # Otherwise comment out this line
  
  #Requestor Value
  Ar = matrix(data = 0, ncol = Nb, nrow = 1)
  #Validator value
  Av = matrix(data = 0, ncol = Nb, nrow = 1)
  
  #Firms-Banks credit matching
  link_fb = matrix(data =0, ncol = Nf, nrow = 1)


  
  
  #INITIALIZE THE VALUES OF VARIABLES REQUIRED TO START THE SIMULATION
  # Total value of validator and requestor firms
  
  Ar[1:num_requesters] = 10
  Av[1:num_validators] = 10
  # Setting intial random prices for firms
  price[1:num_validators] = rnorm(num_validators)*varpf+alpha
  link_fb[1:Nf] = ceiling(runif(Nf)*Nb)
  
  for (t in 1:Time) {
    #HERE BODY OF THE SIMULATION
    
    # order of events for simulation
    # i.e. each round new batch of info comes for attetestation
    # Intially assume a stochasitc distribution of requests?
    # I.e. each requestor will get a random number of verifications to perform
    # a random sample of say 5% of these requests will be with falsified information
    
    # 1) the requestors choose which validators to send their requests to (This complex linking step to implemented later,
    #  as a function of price charged by the requestor and also including switching costs)
    # 2) requestors send the requests to validators
    # 3) Validators send back attestations or mark the flags as false
    # 4) If not marked false, requestors pays validator
    # 5) else they can dispute etc...
    # 6) Note we can say add a probability of say 50% that Validators find documents to be false given they false
    # and say a 0.5% chance they find them to false, given they are not false etc..
    # We can adjust these above dynamics and we will set them up in the begining
    # etc the whole game theory plays our every round in this loop
    # and the consequences rewards etc for punishments etc..
    
    # Then we will consequently calucate all the different firms profits and performances over this period
    # based on this the firms will update their prices???
    # Then the loop will run again, and note the first step, links between the validators and requestors will change 
    # based on the prices that have changed at the iteration of the last loop
  }
  
  
}


